name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - run: nix flake check --print-build-logs --max-jobs 2
